---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarqube-secret
  namespace: sonarqube-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgACxpUjjvXqDlYJdviSJCoUHGhCtVydD35WbfS++wWPL/IGfY/2APjlRQ+TN7TKnv7NFQFquUx2D9K4QFocQcMw3+gsx4RuKUgq56gk7UYpPAp5cXjkUOR7SZSQFf0ADqMjPfP/FunCzXIBIEaKxLLue3zXElNhSQ1d+LKz9yfWwiR7SrOD9eDleiOUw3eso2sdZ8Ab3S8cSAG2T2i1OmwaiXx3uDrE17/PoRtSX5Sv03n5jSPkDXxxC1msAGKAHoX2vfGc0j1219U08MLZ9qUF8ndSRrgKg1qkG0Hqvc7vepU9gLS8+SS0SWZ54L+o3aD0AlrX/a2uDuSPOaqsXq86JRtJ3eiAv7p+h44v7laJADqJLSmGEVSezRreMXDiVOpLSOQbhMhmz3BINHb0+mdDaBsL+mNUeFrHby3vM8wAtTjOh+gtb3c8HTdzJSA+lfvuW0JHqGdsui/tAgG8pMOWP9ovkSYenOh6fDUnlphVjXwignTwbm1JmCfrt39/KHTx9QbUdDU7epeRmgEf/s3Wtj0hlPSatcDn3l7Q1o9OGzfU388P/KHb50KhXTCi7vRetSRMe8yvgdNTZVZGRaMi7IgW9sA1ltz4/emYrwN+04CIEzCbDnCxBlcxQEXDlN6EFTlGY/wde85rJRw5kZ32a3MTSLRB9ZWPh/YGcR9ZH40SanVF7eSuq9p//M5uyvimAcRcOgVVJVtRxkR27mBmcVtqTmapLonZmmlBz8Mr
    SONAR_JDBC_PASSWORD: AgAwjPnx+w8U778PNvL06M3G+NkPgcGg46OX4OKdQbIfVDfka5nRJxwszaQBqyQ/PGkZfRqPl13991nVHNgiKMgU3SLdo11vK+r18gB8SsMzquA7v1InyrcGZ31YneUaLctvBpKrvLY27Zr9lZRfDQbzG31orejEgwv6NCafGJeHzMGz2JUppijv80UAswTZPQrgJFG/p1wp2wkUwyx9nVHc0lqM4TvqjSaQYiKZIZcrfdXkG8Td7IlkDHoDpbOZoKzTG0eh6dxKooZ7/SQVb4N1GrJKvMqwvZrhzbTL3PskxnMe/Ypx868RAnHry2+597EO2PWCeQtCAH1RTAs/CuUR8M6y6B+ROhIidlfqsYd2GpVg8sOZxLy1UIfnSxPgALkNphSP3K9S4lbd1E4GgrVqx0HH/OZULTtQEyU9/akC2qKD6eeTGNvU65BKnOnNvgyWMWisP9nCXHikCb1iGpFq9fpIPkky2kHqmSuDiNwKlF/EigsAGY3PO9sH+6t3I2jZjI2QjikjLxQIdekASnhFn5htjx4Xo5p6qPSI4HwoCyBVLFt8sZ8FydScLKQAcjhpiuSFJWJ05h8J3t5/M35rseS1et1klBe32z9mllqpvoCMLpXPgeXPFx8/tsGatUj4sKj7Gl9uIPqOrz/nJrVuGTzrQxOQFtxsPDCfVrQf4Xb8kqGn7JQVR/iuV5noMmqd4JEuaCVYpRzbKnSBmBpQPrI12WuhAkdJpYt7v4Pd
  template:
    metadata:
      name: sonarqube-secret
      namespace: sonarqube-namespace
    type: Opaque
