apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - onabudget.yaml
  - onabudget-sealedsecret.yaml
  - registry-pull-sealedsecret.yaml
images:
  - name: registry.andrerimes.com/andrerimes/onabudget
    newTag: main-5700e21
