apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - onabudget.yaml
  - onabudget-sealedsecret.yaml
images:
  - name: andrerimes/onabudget
    newTag: main-d7b91ce
    newName: andrerimes/onabudget
