---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-pull
  namespace: onabudget-namespace
spec:
  encryptedData:
    .dockerconfigjson: AgAMenpPk0AX1BAZ/OyZ9LdjZeegon+qMxutJGqARuB0Urm6nX9C/1HTy4oIoetJe/QeAYLBAzpgv08+GtGQmnD3SmaSACunapgVVF568npyNjF5o8+DzYLZ7OkJohAHrSryNqCCgeDLg3VswUNlqWcNk0bjVcU61nN+0RYfGSwP9RV0Whfwwcrwn9Mlk0BS2AGMc1auEzq3Nd2jYfh1ZxX3bvUHsknzHCziVJQS/y6XA0KPkxXTejKDwljumwchixl75ViBNkK36dS0e73obv9yw+op1c7C2PHzVxhpPupbgVIBqWjHFqT7iw6uQARMBrTuzz/bPSIi8nrUVbliAcE+j4QGOve5TPlRgOHWi4A2YUXidnL6MTwGYAiaz8xIROvfkZ+NSHFutyUJe70TQKH5vpr8NIkIIhzyJbd6bfHxUiTGREbsbd6TpKr4tMo3PKXb0ZyI6++FbooNVlAnLpbae/5f/5y8fDr+X2Awz2LGarSfZ6MVa/C5tmYjNz5JtysUXR2+Vp70ZK+EyipqbxCkp/mlQiw+1MZsvKlBZv2C7SKYYkArkNkcLEE9dqnguKSPxA3K/xkTMnv5WH/2dVxCKDD3XeDvSou8q/iX2to8ezYG+RO9F1SFRkkqTArUW5q/IbsDQ0TyC7Ag2KktqJchc1T2FzxEDPcxWVTtGeUHovj7wmlulpPM9Cusr0eXVp1ULKiwfwKQVZJKhz/+LzOT6lFw4jjulTb3vxU0nhd70pcZmbxtS0/lPMqeoxRpWaANei8gv4un14+bbGTawirRGK6Xm0VvsbNofCdkqwKXnJjESrR+mXRDFi66kJNKmgfVRxAUAAsGYJMNVnz5z+e8G+xEat3xLc720XySp5RWXvnIel++yeLlTpsIyyxDMcHX+HL0rnpxSZcucYVITTJGRslsHRt23tB9MWFd2tty0jrcxDlq5J2VjkERCYwe7E9hQ/Ud+LzooZHLzIGN1S70/XT0gmJ1N0Q=
  template:
    metadata:
      name: registry-pull
      namespace: onabudget-namespace
    type: kubernetes.io/dockerconfigjson
