---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-auth
  namespace: registry-namespace
spec:
  encryptedData:
    htpasswd: AgAGExAeEpTDWHkBKvMBNW+5RVR8NYrzs1GHRoEy2Aulo0T1j4Tr83RloxBbIeooU2+0BF0EYN68byBE+R7UIwaJUnelX3U5kyNJoBbtWgrygr7Y4FiKLNv6rACylvxSoXPepKjR8LodSELhjGZ6DVsPWlBHuJrofSrKPAibSBEO67wfmNT6ujnrEA7GnQsCgBtUrV+GRWoZLR7mYlcVCCUe5fe9VMeXmDoDkme7jzjXv7WeiznDnj7Qrt6A+C7f5eS6eVWr9xBLrUZzZ/Q7extom30FsEocPj1FeaQMDxTMd/DwgJ+B8a2reBWqgtTCKtqsKmLu/QIdb1QWGnO23jYdKQQ/OJvIN1PE0pRn4JV9Jmx/2x/I23IoiwAn93itFnCtwTpyrBoab5X7ouhhPVtPkkGtitu1sWw1cx0e/2tqH7fD5TZbw0CUbjIxn9W68sVkcvOLtoBEv/c1UOa7DEapI+4sL3V8Rfc/nILrejkBJw9c9PLBIxCnVt4kyL6Ub/GrNH15S/gXo/OXdF+vxJ1xb1/jXQl7G8B8Wta3sywNsgwAWcLDuYFLnbGNMRAREjCun0UcQtFsGtE8kQBhVuGX+0f5/xnkUMCCrqKQd0JdRPlx1wFEvXnpZl8/NJGfGt6yA0pU8oDlAUkwz7mXLZtiFAOIQ5NH4H8rXOVkKwyzHKIjLdOzLIiE2kZZMkcmDYMIOq7fypIFEvsKB0Z8gawhPTcvhVrmMadcpFe3O9h//RXGv/89RcB6694t95dijtQMWccn/Is6wfHuRqHS/PBUMm91OxV9mQEKBDBXAP3LuI38PXYlERACoIyFkQsQWaJzn1pk2V/OQser0Vebjh8n6f+50zf6zQBs78lD1Gg4uQe8MwDZMo7/8rf91Cn4VFZeGadH8g==
  template:
    metadata:
      name: registry-auth
      namespace: registry-namespace
    type: Opaque
