apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-auth
  namespace: registry-namespace
spec:
  encryptedData:
    htpasswd: AgB63xTIFeuD9LnazZhL+2vF4QTPZCQeD65UHnrHUc4wsRZ/8pXQUvbvUo41ZVGHk3z9MSKEesU2E0+hblnqrB62XD4DSvwTGNTIVJWUILaFIQpcUIMWKjPcwWeVJpz89hVfemvRb4UBgxPh1u4TkMnELe5/47izc/PXJMlKhg3IjuXZx5Se/elWdNgBmuoj6o1ZoxChQGJ53Z6vLOX4fGBiIpNfnacg+mAShkZyqVfCkz6sy78Mrxctff45rN+o/om6lhf5C7JydBV/q2v7hAoX8lBoLJFDsNsmdEZWnv0j6OJrrQiDx43qfkQgMue/b3t6pneDFsxTVxQeMm6kZHLGnEVpWl3XPpkmvNKxxCiJviFwLnEM3roLM3fbf8iLDT/X2k6adata/2wUidnYfluktoAFHAN6MO8EBtALqyLwARQ1uRy+RusTjzgjMKIH6GV7QjfomRBXR52KECA1+d0koAQYZzyITvI0pHFlHvvs7H0VURRCHZUZb8+PANznG38FfmUENEopNjDmLWjxZu+2ClX9ULWnppCbXLqD8/Bedz/GaFa3EwLY0IMBSN+rGVrYnDt+/8QSSCQKpxSf7mYhYKQHfrmM7JXrjprxR+o08AHuNqLGxz4QNdQPy1564L1RVfchJYjE1+R/XgWjyHyDFw2Q0akt+tOV0nYaYFfXTavcc+mNsuJHA5viU54jbvSh+ZWKHtpXd7uwp8IzNERx/yPxr+ClS9wbtoHr3zMDPoMvF3C05qfMgqfpKXpPTRGBhIWQr8VNJmTl4gOLMXGuRMUsCx+STQ==
  template:
    metadata:
      name: registry-auth
      namespace: registry-namespace
    type: Opaque
