apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bidnow
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/AndreRimes/IAC.git
    targetRevision: main
    path: kubernetes/apps/bidnow
  destination:
    server: https://kubernetes.default.svc
    namespace: bidnow-namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
