apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onabudget
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/AndreRimes/IAC.git
    targetRevision: main
    path: kubernetes/apps/onabudget
  destination:
    server: https://kubernetes.default.svc
    namespace: onabudget-namespace
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: onabudget-deployment
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
