apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/AndreRimes/IAC.git
    targetRevision: main
    path: kubernetes/apps/portfolio
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-namespace
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
