apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/AndreRimes/IAC.git
    targetRevision: main
    path: kubernetes/apps/sonarqube
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
