---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-pull
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgCe+/J7udsYYhrEIaXFBb7hdE6Gkw3o+k8PqTaFJ4IOvBwEH4KJw9bxBTkTJyC+UMfaj5FaE7Nzzzuo8Ohz2eyqkEYLBxYpfAnm3r9CAxdevkcwPjrGfqYFf6Bfh1NFUgy6QcOea9mbqjfEADwoAxx3Vm1xiGsLSHw5LqndyUuH+g9CtgchGbQ/TmYXV/YupYZoDqj+ddPbaBn5XsAvVAFhtS7BWViv+0ItffO2bVBXFeVSI4v7DC1di+sEMZrM32fBD1pgXYTmwZcgrL8REP6CixEztEyTWARlWZJqQIPzNTwoskePxIL3ekWPTeXyrvvGH0H9WmzBjmu25tq5LlZqzyXmdzNMeUpQXswm+XZUcaCh6IWlygEsy5Pk4IuGnrRjRdoGKcyZb8NJwYWms1tvFxhyfN2pXaYNRyL+GMESVOyQJ8Sr1AGf6tug/MsE2EhLKEQRW8QXCu7AkzrUIdpou3q15sSTmTh7VqPLXNLnGIJ01M2Vm/wO65HC6jQjQzUv5FcEag2lljHe6mWNyFo63+KKXJEuTAZgsHhCFKm6tvylQMy4iBP+nspFyG6qVNz5HwRsqFkl5FOYjT1QaJKTnq8e8ZZwOPPErbP4vZEfpxvjUnOuqP16yf8N+3z6uoh1AF6Nt6l29u45B/5A/aeOkJlOc7S2X1HJQaIQjj1Wd5QAmXFelWyz0FROzvrap9fMLzHm8i5npgPhxCrCNbB4/Cpd63Zy90f+3rSqicbTiZtVu69Ry/Y5YX6Y8/WUCTUMMM2zydt/c5AiwE5VTN0xRtSkEdnJR7ONK7cxSrSMdTyO/30o/j5arYa1z1GyhXe0bs/YPPEDUrIEJPIs3lNrVf5XwZZ9CNZ+I6FsvgmNRyrIY63cQ7Tz4Rb9/MMHpRpSmyIvbSRj2FtTCgQhy3/vRyORe0Yv1iT115mFoGBlIx69eSoM1qKdbcIE67CttPCeklv05sX6tAzQjSlztWK68TYskuYtqq0=
  template:
    metadata:
      name: registry-pull
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
