apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - bidnowback.yaml
  - bidnowfront.yaml
  - bidnowrecommendation.yaml
  - postgres-sealedsecret.yaml
  - backend-sealedsecret.yaml
  - recommendation-sealedsecret.yaml

images:
  - name: andrerimes/bidnow-front
    newTag: main-135977a
  - name: andrerimes/bidnow-back
    newTag: main-552a3ae
  - name: andrerimes/bidnow-recommendation
    newTag: latest
