---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bidnow-recommendation-secret
  namespace: bidnow-namespace
spec:
  encryptedData:
    DB_URL: AgAYGWKz/x/40eOAIuMPGJ+rJmk9EMjS3GJUtjFu/pHsiUsLdS+G4NQolV868yKuDdlfDOZvGRmvOUVXlq4xq4slO5R3oTK/8s2QeWwxOaDgzseV64pdpL7/5yomGHhQNlBvkQmiJLSUFUB7qfyiCO0cwmJgnTGlhi4ORNDOToX/nE9Elmsk18LjWDU240RmGzBobrmFgJ/4zHwoiPsU2kf5i0lKBEgLAi+dsJYeH140t77KIXkUmhQUmrmoS7MXor3Ugwf/BysMD0g3cuJ+xQHJJBkGW8e4mdEEuk6n1vmcQSlHsssCMHg9rkbCtw1PqGGM/FnCNQG7zooZFlRtrvAfuVNxGP8hpGy6bCoq40AFdv6zuqQK/9ME83kjAzKXAOjCEg/oYF6AaVhr/wRPs8h3kWkbgosj0LiZK3Fd8HPsSX8p/f5fNte4OYUy4p7T7RqP90wi0lAzheHPwFy6pluFRgK+bgevzX1t7OZ+FFn0tV2rqiDRPErt2adnnhE/iEXbl3gOj2Jv3AFniXmeRN3Tt/6wm42MbeeHai2YWzdHn+YdytPPcOe8U/2YTg/L72wexNLkngCQbKlksllDzfw5mSjZRv46Q0pznbXx3DcNhw6HMHup4XFQDPG0+XmhPrCzoTmhIR7fo0CyuYg2LWn6gQXQaFcJf1bytOiYLuKzadpMeE6NWBJrmfOA8XQDk+vPMllPT1pvWj/jlcCWMAgTgrZqruDQ01XJcaHoscw4iGBdHT8O5nVxzkycpBg7BnFS174g2E9BplSTpO+cys87DGY5NYg=
  template:
    metadata:
      name: bidnow-recommendation-secret
      namespace: bidnow-namespace
    type: Opaque
