---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-pull
  namespace: bidnow-namespace
spec:
  encryptedData:
    .dockerconfigjson: AgBRnpO8rXewN1mK2EfEL9cdsbS/ZzN3+lO+Qx26ibwSv56BH1DgvPtI8rgzv1hQzGArzLWG3wUJiFZhLXNObiPaBBtl2SCAQ9pF8gAjkSgshetmdIVjeleECZO0GLptKF9uG3mu67PoF9JMypUvVHj1HDgQCRS8n5eL3juCG/cYqlev0EL7EpwDjCDLLCNj275dZTzR1OED5YCUaKqRq6MuR8ojPz/rKo+H5/lQhNYZagd3YATlVTzaHUW1e4i8tqiAD0mpFbPy96WlAlNZ3XsR00V7iwk3zwR1lNXJgyB7C+51/UMPGlxj5ULKrOfrfXJlGbgiDKZ8CzMS/nJLyUMKhSLOxa+m/ox0Ewi70ODTZRiU2RsiiLXnvIiKgoU/ky6zaq29Mc6Q2PVSUSpgKna814OR6jTstQkDM5yP6AckGnXjjsqFPTgk7kwijmcyWHIcRUsSDxMDLDlHdktvyy7FQBiYVINyGOy6Tkzk4lLoIT8v86wjVikHW4+aeWCEv5Z+YUpdehaFg3ziiP88GBFIx9uWZKVivy7R+TbL4Xhx3EYjMKfjIPJzW9jTzo2tmD00ak0Yo5wefi8GKfoU/tS6pqoDIwIdtApRqVlbAvlhgZGyUBqRVSV9+5OOEeFWXMc1Yp6MDil3lw40Si2bMN6vY3pZ9RDI5Aw9+pllMxHx+78gpTv/MmDHqmdjRCBM7cSovPiIahdbejGs/jEgd4O/mssmprbjjW8W5MqkL/4cycsN/+3XmkHRZ0fBq7IL1PFm01IpD6lE2cEl2qs8YOwXMIVEnGcqUDL5pB4qSAcjadMfUc9ibPrJextfKRvwtDhCCHajzz2VWutDerTYsTbsyidYIYWEBhbJsi6oL8h/IO1koPo7nwrLtIwT9D30OBe0dVTsYo+bY7O2EvEYafuyNtZCI1fqhXaLqMtiq3aSIpynAStGD0YcAQR9A7TJo+kgMvEqLqwYZHIbtgrVV0U1BFJ+ue+qtPg=
  template:
    metadata:
      name: registry-pull
      namespace: bidnow-namespace
    type: kubernetes.io/dockerconfigjson
