apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: global-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
  - host: bidnow.andrerimes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bidnow-frontend-external
            port:
              number: 3000
  - host: bidnowback.andrerimes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bidnow-backend-external
            port:
              number: 8081
  - host: bidnowback-ws.andrerimes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bidnow-backend-external
            port:
              number: 3334
  - host: bidnow-recommendation.andrerimes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bidnow-recommendation-external
            port:
              number: 8000
  - host: portfolio.andrerimes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-external
            port:
              number: 3000
  - host: onabudget.andrerimes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: onabudget-external
            port:
              number: 3000

