apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - portfolio.yml
  - registry-pull-sealedsecret.yaml
images:
  - name: registry.andrerimes.com/andrerimes/portfolio
    newTag: main-25bec95
