---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-pull
  namespace: portfolio-namespace
spec:
  encryptedData:
    .dockerconfigjson: AgCUY0QCfGOYQrrvmlacUsaxNJlTgDHrisAuuipLhEq7DZ6uSIl9HQEdn29iakFKiPJEMyd48jwKtTuKGJX92MrQUSmp1fXc4fBI09VUbGVRC20Axl6W8RqtCutE3ih5l6bZfsk65CeSm1+Rk7L2+4pQ/fag6CUvEhq01AVbodkPbZSmyjfURX86fjcvZrrWmZ/3aOsgD2Zze195c4+r/kiZi1CMR4RPZDl+NCeJHgE+h0Z8BGRtcIwUNPqIwqpQ5JRh8bKIWJ49pmOWNMeNUFVsgj+k6w6yZvwLu3/I7XU8DOwNa2RWQHJNEOQ8+qeaMCiAOh7j9FXMFVo1aFyAUJ/V7BNtEH2IE17xIP4OaCz244Ns04lPRiax9Wz4vKW6iVvYVeaxRjdsJ6KYnnO30a7ljIpcOy8+vO4JIoznK6DcfZbi96D/SQupPXmVX3rjIW/xetRHQw13lSbkQYV/01hxkPIcjqa63TM7t/lBlrb4TM0giWT7rFT6Y0Ekg9v6sOdz6ptTpQ+TCDOyO3T1fGVMoHDOiD4bv9DFavjLdDWgtWW/IzHEbWjjUVj5SrWBnQIFLjj6FYe11tjVI9+haxhhYrO6zgPPRkCYJsliHM+r7naCfza/d7g0lcTqbefWzWVPvmo2T4BrHwTJBINTgCuetEbsnTiQOCOGuKr5BxX9OCf1X1Pe9ePGsfqR7dmVLUxRQvCrmqEekQhj60HAblOzGseH3Qs581VG0FKFcnUd7pDFfLgYmr22U7As9+PDHU9zrQ4sBPdOGfW6xdWLlchYU0788BJ1Gb5YbLhm6afKxUFCKsmAfFg63u9sS7HUtUr3e/UqTyk0QoLsPOXrawEySE2WiRBqnUBvhuU1uMDBllkRPfGgMKhpUSZzrWhsMkw8LLJh7+dQzu7ehMTREJ3xy/BtouqrpgTfVXdbzl1xkPoKwh9xbsfiCcZIGJ3nWr35K8F3mSJ25BM9VNEfzErZ5yuRtCDeIB8=
  template:
    metadata:
      name: registry-pull
      namespace: portfolio-namespace
    type: kubernetes.io/dockerconfigjson
